--- #Full include tasks example
- hosts: apacheweb
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/pakages.yaml
    - name: Verify the telnet package is installed
      shell: yum list installed | grep telnet > /home/ansible/pkgs.log
