--- # My first yaml playbook for ansible
-  hosts: apacheweb
   become: yes
   connection: ssh
   gather_facts: no
   vars_files:
     - conf/copyright.yml
     - conf/webdefaults.yml
   tasks:
     - name: install Apache we server
       yum :
         name: httpd
         state: installed
       notify:
         -  Restart HTTPD
     - name: ensure httpd running
       service:
         name:  httpd
         state: started 
   handlers:
     - name: Restart HTTPD
       service:
         name: httpd
         state: restarted
