--- # notify and handler playbook
- hosts: apacheweb
  become: yes
  become_user: ansible
  connection: ssh
  gather_facts: no
  tasks:
    - name: install apache web server
      yum: pkg=httpd state=installed
      notify: restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
