--- # PROMPT FOR USER PACKAGE EXPLAME
- hosts: apacheweb
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.0b
  vars_prompt:
    - name: pkgtoinstall
      prompt: install which pakage?
      default: telnet
      private: no
  tasks:
    - name: install the indicated package
      yum: pkg={{ pkgtoinstall }} state=latest
