--- # test playbook
- hosts: apacheweb
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: dleting it
    find:
      paths: "/home/ansible/"
      age: "0d"
      file_type: directory
    register: directories
  - name: deleting all directory
    file: 
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ directories.files }}"
    
