--- #to collect logs  
-  hosts: apacheweb
   become: yes
   connection: ssh
   gather_facts: no
   vars_prompt:
     - name: log_command
       prompt: enter log command       
   tasks:
     - name: collect logs
       find:
         paths: /var/log/
         patterns: '*.log'
         recurse: yes
       register: _logs
     - name: fetch logs
       fetch:
         src: "{{ item.path}}"
         dest: logs
       with_items: "{{ _logs.files }}"
